# Don't forget to enable cors on the backend, when the api runs on another
# domain then the frontend.
api: <the base url to kwai-api>
contact:
  title: <Contact Title>
  mail: <Contact Email>
  address:
    street: <Contact Street>
    city: <Contact City>
    tel: <Contact Tel>
  facebook: <Facebook group url>
  location: <Link to location>
  website:
    url: <url of the website>
    mail: <mail of the webmaster>
    webmaster: <name of the webmaster>
website:
  title: <title of the website>
  hero: >
    <hero text>
  promotion:
    title: <title of the promotion>
    text: >
      <promotion text>
  information_boards:
    - title: <title of the board>
      text: >
        <text of the board>
      # Put the image in the public directory (or a sub directory of public)
      # The public directory is treated as a root directory for the link.
      # For example: if image.jpg is stored in public, the link is /image.jpg
      image: <image to use in the board>
      bg-color: <background color of the board>
